import { OrderStatus, PaymentStatus, type Order, type OrderItem } from "../types/models";
import { fakeRooms } from "./fakeRoomData";
import { fakeProducts } from "./fakeProductData";

export const fakeOrderItems: OrderItem[] = [
  {
    id: "1",
    orderId: "1",
    productId: "1",
    quantity: 1,
    price: 999.99,
    product: {
      ...fakeProducts[0],
      cartItems: [],
      orderItems: [],
    },
  },
  {
    id: "2",
    orderId: "2",
    productId: "3",
    quantity: 1,
    price: 79.99,
    product: {
      ...fakeProducts[2],
      cartItems: [],
      orderItems: [],
    },
  },
  {
    id: "3",
    orderId: "3",
    productId: "4",
    quantity: 1,
    price: 129.98,
    product: {
      ...fakeProducts[3],
      cartItems: [],
      orderItems: [],
    },
  },
  {
    id: "4",
    orderId: "4",
    productId: "5",
    quantity: 1,
    price: 899000,
    product: {
      ...fakeProducts[4],
      cartItems: [],
      orderItems: [],
    },
  },
  {
    id: "5",
    orderId: "5",
    productId: "6",
    quantity: 1,
    price: 2499000,
    product: {
      ...fakeProducts[5],
      cartItems: [],
      orderItems: [],
    },
  },
];

export const fakeOrders: Order[] = [
  {
    id: "1",
    totalPrice: 1129.97,
    status: OrderStatus.Pending,
    paymentStatus: PaymentStatus.Pending,
    createAt: "2024-03-15T10:30:00",
    updateAt: "2024-03-15T10:30:00",
    shipAddressId: fakeRooms[0].id,
    shipAddress: fakeRooms[0],
    userId: "1",
    storeId: "1",
    shipperId: "1",
    voucherId: "1",
    items: fakeOrderItems.filter((item) => item.orderId === "1"),
    user: undefined,
    store: undefined,
    shipper: undefined,
    voucher: undefined,
    reports: [],
  },
  {
    id: "2",
    totalPrice: 79.99,
    status: OrderStatus.Processing,
    paymentStatus: PaymentStatus.Paid,
    createAt: "2024-03-14T15:45:00",
    updateAt: "2024-03-14T15:45:00",
    shipAddressId: fakeRooms[1].id,
    shipAddress: fakeRooms[1],
    userId: "1",
    storeId: "1",
    shipperId: "2",
    items: fakeOrderItems.filter((item) => item.orderId === "2"),
    user: undefined,
    store: undefined,
    shipper: undefined,
    voucher: undefined,
    reports: [],
  },
  {
    id: "3",
    totalPrice: 1299000,
    status: OrderStatus.Delivered,
    paymentStatus: PaymentStatus.Paid,
    createAt: "2024-03-13T09:15:00",
    updateAt: "2024-03-13T09:15:00",
    shipAddressId: fakeRooms[0].id,
    shipAddress: fakeRooms[0],
    userId: "1",
    storeId: "1",
    items: fakeOrderItems.filter((item) => item.orderId === "3"),
    user: undefined,
    store: undefined,
    shipper: undefined,
    voucher: undefined,
    reports: [],
  },
  {
    id: "4",
    totalPrice: 899000,
    status: OrderStatus.Cancelled,
    paymentStatus: PaymentStatus.Failed,
    createAt: "2024-03-12T14:20:00",
    updateAt: "2024-03-12T14:20:00",
    shipAddressId: fakeRooms[1].id,
    shipAddress: fakeRooms[1],
    userId: "1",
    storeId: "1",
    items: fakeOrderItems.filter((item) => item.orderId === "4"),
    user: undefined,
    store: undefined,
    shipper: undefined,
    voucher: undefined,
    reports: [],
  },
  {
    id: "5",
    totalPrice: 2499000,
    status: OrderStatus.Pending,
    paymentStatus: PaymentStatus.Pending,
    createAt: "2024-03-11T11:00:00",
    updateAt: "2024-03-11T11:00:00",
    shipAddressId: fakeRooms[0].id,
    shipAddress: fakeRooms[0],
    userId: "1",
    storeId: "1",
    items: fakeOrderItems.filter((item) => item.orderId === "5"),
    user: undefined,
    store: undefined,
    shipper: undefined,
    voucher: undefined,
    reports: [],
  },
];
