// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ResiBuy.Server.Infrastructure;

#nullable disable

namespace ResiBuy.Server.Migrations
{
    [DbContext(typeof(ResiBuyContext))]
    [Migration("20250920122826_mmm")]
    partial class mmm
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.AdditionalData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductDetailId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductDetailId");

                    b.ToTable("AdditionalDatas");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Area", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Areas");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsActive = true,
                            Latitude = 21.0227,
                            Longitude = 105.83629999999999,
                            Name = "Default Area"
                        });
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Barcode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("OrderItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ProductDetailId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderItemId");

                    b.HasIndex("ProductDetailId");

                    b.ToTable("Barcodes");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Building", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AreaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.ToTable("Buildings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            AreaId = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsActive = true,
                            Name = "Default Building"
                        });
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Cart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ExpiredCheckOutTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCheckingOut")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.CartItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CartId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ProductDetailId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductDetailId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f2ab22dd-7125-444f-96ec-38b8772bdd18"),
                            Name = "Đồ điện tử",
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("71983420-b7b7-4394-86c6-9835e10ed0df"),
                            Name = "Thời trang",
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("2b74ff47-0753-489e-b475-939fbf090cc8"),
                            Name = "Đồ gia dụng",
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("ada725ac-50fe-47de-8e5b-724f78cf54eb"),
                            Name = "Sách",
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("be7419fc-469e-4287-ab06-4dd0efc99fe6"),
                            Name = "Thể thao",
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("9f763e26-bbf4-4608-ac7e-4d83a26ea940"),
                            Name = "Mỹ phẩm",
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("a57bb77b-e240-400e-aeb3-ffb0541eb6e8"),
                            Name = "Đồ chơi",
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("a5f0ed90-cc04-415e-9268-0450fb5ce07b"),
                            Name = "Thực phẩm",
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("e85e9291-1598-4e88-bc43-6c3f151b14b3"),
                            Name = "Phụ kiện",
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("faba4d2b-c19c-41a6-a539-4595478f7fc3"),
                            Name = "Nội thất",
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("a2747dd2-fe87-4709-8e39-5ae83a2e80c3"),
                            Name = "Khác",
                            Status = true
                        });
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("StoreId");

                    b.ToTable("Event");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Image", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProductDetailId")
                        .HasColumnType("int");

                    b.Property<string>("ThumbUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId")
                        .IsUnique()
                        .HasFilter("[CategoryId] IS NOT NULL");

                    b.HasIndex("ProductDetailId")
                        .IsUnique()
                        .HasFilter("[ProductDetailId] IS NOT NULL");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            Id = "085145d1-07a8-48c5-ab01-15208c9a500b",
                            CategoryId = new Guid("f2ab22dd-7125-444f-96ec-38b8772bdd18"),
                            Name = "thu-mua-do-dien-tu-1.jpg",
                            ThumbUrl = "http://res.cloudinary.com/dhz6zqwxx/image/upload/c_fill,h_300,w_300/string",
                            Url = "https://res.cloudinary.com/dhz6zqwxx/image/upload/v1756314488/string.jpg"
                        },
                        new
                        {
                            Id = "b2f092c2-7934-424c-b298-382b963d4dd3",
                            CategoryId = new Guid("71983420-b7b7-4394-86c6-9835e10ed0df"),
                            Name = "thoitrang.jpg",
                            ThumbUrl = "http://res.cloudinary.com/dhz6zqwxx/image/upload/c_fill,h_300,w_300/v1/resibuy/thoitrang_usekdn",
                            Url = "https://res.cloudinary.com/dhz6zqwxx/image/upload/v1756314610/resibuy/thoitrang_usekdn.jpg"
                        },
                        new
                        {
                            Id = "d9887ba0-0b15-4afe-afeb-98313f10a214",
                            CategoryId = new Guid("2b74ff47-0753-489e-b475-939fbf090cc8"),
                            Name = "dogiadung.jpg",
                            ThumbUrl = "http://res.cloudinary.com/dhz6zqwxx/image/upload/c_fill,h_300,w_300/v1/resibuy/dogiadung_u5cuyh",
                            Url = "https://res.cloudinary.com/dhz6zqwxx/image/upload/v1756314610/resibuy/dogiadung_u5cuyh.jpg"
                        },
                        new
                        {
                            Id = "fca1435d-caf9-49f7-9e06-7d3beca3b270",
                            CategoryId = new Guid("ada725ac-50fe-47de-8e5b-724f78cf54eb"),
                            Name = "sach.jpg",
                            ThumbUrl = "http://res.cloudinary.com/dhz6zqwxx/image/upload/c_fill,h_300,w_300/v1/resibuy/sach_w9rqwe",
                            Url = "https://res.cloudinary.com/dhz6zqwxx/image/upload/v1756314610/resibuy/sach_w9rqwe.jpg"
                        },
                        new
                        {
                            Id = "086ccadd-238e-4d79-8f3d-1e336425caca",
                            CategoryId = new Guid("be7419fc-469e-4287-ab06-4dd0efc99fe6"),
                            Name = "thethao.jpg",
                            ThumbUrl = "http://res.cloudinary.com/dhz6zqwxx/image/upload/c_fill,h_300,w_300/v1/resibuy/thethao_mv34he",
                            Url = "https://res.cloudinary.com/dhz6zqwxx/image/upload/v1756314611/resibuy/thethao_mv34he.jpg"
                        },
                        new
                        {
                            Id = "e321893b-0163-49b9-a79e-43910af56097",
                            CategoryId = new Guid("9f763e26-bbf4-4608-ac7e-4d83a26ea940"),
                            Name = "mypham.jpg",
                            ThumbUrl = "http://res.cloudinary.com/dhz6zqwxx/image/upload/c_fill,h_300,w_300/v1/resibuy/mypham_iltnhv",
                            Url = "https://res.cloudinary.com/dhz6zqwxx/image/upload/v1756314610/resibuy/mypham_iltnhv.jpg"
                        },
                        new
                        {
                            Id = "1e82a467-a515-480f-a186-6076366fae79",
                            CategoryId = new Guid("a57bb77b-e240-400e-aeb3-ffb0541eb6e8"),
                            Name = "dochoi.png",
                            ThumbUrl = "http://res.cloudinary.com/dhz6zqwxx/image/upload/c_fill,h_300,w_300/v1/resibuy/dochoi_rz7pys",
                            Url = "https://res.cloudinary.com/dhz6zqwxx/image/upload/v1756314611/resibuy/dochoi_rz7pys.png"
                        },
                        new
                        {
                            Id = "1dddb9f1-496e-43cc-9f9c-820395e2f9f8",
                            CategoryId = new Guid("a5f0ed90-cc04-415e-9268-0450fb5ce07b"),
                            Name = "thucpham.jpg",
                            ThumbUrl = "http://res.cloudinary.com/dhz6zqwxx/image/upload/c_fill,h_300,w_300/v1/resibuy/thucpham_la23wq",
                            Url = "https://res.cloudinary.com/dhz6zqwxx/image/upload/v1756314611/resibuy/thucpham_la23wq.jpg"
                        },
                        new
                        {
                            Id = "719e2312-4b77-4a2a-9242-e87435830a14",
                            CategoryId = new Guid("e85e9291-1598-4e88-bc43-6c3f151b14b3"),
                            Name = "phukien.jpg",
                            ThumbUrl = "http://res.cloudinary.com/dhz6zqwxx/image/upload/c_fill,h_300,w_300/v1/resibuy/phukien_sct8nd",
                            Url = "https://res.cloudinary.com/dhz6zqwxx/image/upload/v1756314610/resibuy/phukien_sct8nd.jpg"
                        },
                        new
                        {
                            Id = "655d22ce-57ef-456f-8525-fb6f2f46199e",
                            CategoryId = new Guid("faba4d2b-c19c-41a6-a539-4595478f7fc3"),
                            Name = "noithat.jpg",
                            ThumbUrl = "http://res.cloudinary.com/dhz6zqwxx/image/upload/c_fill,h_300,w_300/v1/resibuy/noithat_steelt",
                            Url = "https://res.cloudinary.com/dhz6zqwxx/image/upload/v1756314610/resibuy/noithat_steelt.jpg"
                        },
                        new
                        {
                            Id = "0a972d12-9e39-4ad5-b2bf-333f7f516574",
                            CategoryId = new Guid("a2747dd2-fe87-4709-8e39-5ae83a2e80c3"),
                            Name = "khac1.jpg",
                            ThumbUrl = "http://res.cloudinary.com/dhz6zqwxx/image/upload/c_fill,h_300,w_300/other",
                            Url = "https://res.cloudinary.com/dhz6zqwxx/image/upload/v1756315891/other.jpg"
                        });
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Data")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReadBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CancelReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsReport")
                        .HasColumnType("bit");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("int");

                    b.Property<Guid?>("ShipperId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ShippingAddressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("ShippingFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid?>("VoucherId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ShipperId");

                    b.HasIndex("ShippingAddressId");

                    b.HasIndex("StoreId");

                    b.HasIndex("UserId");

                    b.HasIndex("VoucherId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.OrderItem", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductDetailId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductDetailId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Describe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsOutOfStock")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PromotionId")
                        .HasColumnType("int");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("WarrantyMonths")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("PromotionId");

                    b.HasIndex("StoreId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.ProductDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsOutOfStock")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Sold")
                        .HasColumnType("int");

                    b.Property<float>("Weight")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductDetails");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Promotion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Discount")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Promotions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Discount = 0,
                            EndDate = new DateTime(2225, 9, 20, 19, 28, 24, 471, DateTimeKind.Local).AddTicks(9631),
                            IsActive = false,
                            Name = "No Promotion",
                            StartDate = new DateTime(2025, 9, 20, 19, 28, 24, 471, DateTimeKind.Local).AddTicks(9630)
                        });
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.RefreshToken", b =>
                {
                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<string>("ReasonRevoked")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReplacedByToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Token");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Report", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("bit");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ReportTarget")
                        .HasColumnType("int");

                    b.Property<string>("TargetId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAnonymous")
                        .HasColumnType("bit");

                    b.Property<int>("ProductDetailId")
                        .HasColumnType("int");

                    b.Property<int>("Rate")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ProductDetailId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BuildingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            BuildingId = new Guid("22222222-2222-2222-2222-222222222222"),
                            IsActive = true,
                            Name = "Default Room"
                        });
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Shipper", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("EndWorkTime")
                        .HasColumnType("real");

                    b.Property<DateTime?>("FirstTimeLogin")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("bit");

                    b.Property<bool>("IsShipping")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastDelivered")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LastLocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ReportCount")
                        .HasColumnType("int");

                    b.Property<float>("StartWorkTime")
                        .HasColumnType("real");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("LastLocationId");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("Shippers");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Store", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPayFee")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("RoomId");

                    b.ToTable("Stores");

                    b.HasData(
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            CreatedAt = new DateTime(2025, 9, 20, 19, 28, 24, 471, DateTimeKind.Local).AddTicks(9626),
                            Description = "Default store for ResiBuy system",
                            IsLocked = false,
                            IsOpen = true,
                            IsPayFee = false,
                            Name = "ResiBuy",
                            OwnerId = "adm_df",
                            PhoneNumber = "0123456789",
                            RoomId = new Guid("33333333-3333-3333-3333-333333333333")
                        });
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.TimeSheet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateMark")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsLate")
                        .HasColumnType("bit");

                    b.Property<Guid>("ShipperId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ShipperId");

                    b.ToTable("TimeSheets");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AvatarId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdentityNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReportCount")
                        .HasColumnType("int");

                    b.Property<string>("Roles")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = "adm_df",
                            CreatedAt = new DateTime(2025, 9, 20, 19, 28, 24, 471, DateTimeKind.Local).AddTicks(8954),
                            DateOfBirth = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@123",
                            FullName = "Administrator",
                            IdentityNumber = "admin",
                            IsLocked = false,
                            PasswordHash = "$2a$11$u.7UveWg19lOogHcsjXs0eaaqA2vPA/djWKLa9dsRV0sfuJw5f2S6",
                            PhoneNumber = "admin",
                            ReportCount = 0,
                            Roles = "[\"ADMIN\"]",
                            UpdatedAt = new DateTime(2025, 9, 20, 19, 28, 24, 471, DateTimeKind.Local).AddTicks(8975)
                        });
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.UserNotification", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("NotificationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "NotificationId");

                    b.HasIndex("NotificationId");

                    b.ToTable("UserNotifications");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.UserRoom", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoomId");

                    b.HasIndex("RoomId");

                    b.ToTable("UserRooms");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.UserVoucher", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("VoucherId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "VoucherId");

                    b.HasIndex("VoucherId");

                    b.ToTable("UserVouchers");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Voucher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("MaxDiscountPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MinOrderPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StoreId");

                    b.ToTable("Vouchers");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.AdditionalData", b =>
                {
                    b.HasOne("ResiBuy.Server.Infrastructure.Model.ProductDetail", "ProductDetail")
                        .WithMany("AdditionalData")
                        .HasForeignKey("ProductDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductDetail");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Barcode", b =>
                {
                    b.HasOne("ResiBuy.Server.Infrastructure.Model.OrderItem", "OrderItem")
                        .WithMany("Barcodes")
                        .HasForeignKey("OrderItemId");

                    b.HasOne("ResiBuy.Server.Infrastructure.Model.ProductDetail", "ProductDetail")
                        .WithMany("Barcodes")
                        .HasForeignKey("ProductDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderItem");

                    b.Navigation("ProductDetail");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Building", b =>
                {
                    b.HasOne("ResiBuy.Server.Infrastructure.Model.Area", "Area")
                        .WithMany("Buildings")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Cart", b =>
                {
                    b.HasOne("ResiBuy.Server.Infrastructure.Model.User", "User")
                        .WithOne("Cart")
                        .HasForeignKey("ResiBuy.Server.Infrastructure.Model.Cart", "UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.CartItem", b =>
                {
                    b.HasOne("ResiBuy.Server.Infrastructure.Model.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ResiBuy.Server.Infrastructure.Model.ProductDetail", "ProductDetail")
                        .WithMany("CartItems")
                        .HasForeignKey("ProductDetailId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("ProductDetail");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Event", b =>
                {
                    b.HasOne("ResiBuy.Server.Infrastructure.Model.Store", null)
                        .WithMany("Events")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Image", b =>
                {
                    b.HasOne("ResiBuy.Server.Infrastructure.Model.Category", "Category")
                        .WithOne("Image")
                        .HasForeignKey("ResiBuy.Server.Infrastructure.Model.Image", "CategoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ResiBuy.Server.Infrastructure.Model.ProductDetail", "ProductDetail")
                        .WithOne("Image")
                        .HasForeignKey("ResiBuy.Server.Infrastructure.Model.Image", "ProductDetailId");

                    b.HasOne("ResiBuy.Server.Infrastructure.Model.User", "User")
                        .WithOne("Avatar")
                        .HasForeignKey("ResiBuy.Server.Infrastructure.Model.Image", "UserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Category");

                    b.Navigation("ProductDetail");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Order", b =>
                {
                    b.HasOne("ResiBuy.Server.Infrastructure.Model.Shipper", "Shipper")
                        .WithMany("Orders")
                        .HasForeignKey("ShipperId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ResiBuy.Server.Infrastructure.Model.Room", "ShippingAddress")
                        .WithMany("Orders")
                        .HasForeignKey("ShippingAddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ResiBuy.Server.Infrastructure.Model.Store", "Store")
                        .WithMany("Orders")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ResiBuy.Server.Infrastructure.Model.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ResiBuy.Server.Infrastructure.Model.Voucher", "Voucher")
                        .WithMany("Orders")
                        .HasForeignKey("VoucherId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Shipper");

                    b.Navigation("ShippingAddress");

                    b.Navigation("Store");

                    b.Navigation("User");

                    b.Navigation("Voucher");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.OrderItem", b =>
                {
                    b.HasOne("ResiBuy.Server.Infrastructure.Model.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ResiBuy.Server.Infrastructure.Model.ProductDetail", "ProductDetail")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductDetailId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("ProductDetail");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Product", b =>
                {
                    b.HasOne("ResiBuy.Server.Infrastructure.Model.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ResiBuy.Server.Infrastructure.Model.Promotion", "Promotion")
                        .WithMany("Products")
                        .HasForeignKey("PromotionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ResiBuy.Server.Infrastructure.Model.Store", "Store")
                        .WithMany("Products")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Promotion");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.ProductDetail", b =>
                {
                    b.HasOne("ResiBuy.Server.Infrastructure.Model.Product", "Product")
                        .WithMany("ProductDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.RefreshToken", b =>
                {
                    b.HasOne("ResiBuy.Server.Infrastructure.Model.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Report", b =>
                {
                    b.HasOne("ResiBuy.Server.Infrastructure.Model.User", "CreatedBy")
                        .WithMany("Reports")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ResiBuy.Server.Infrastructure.Model.Order", "Order")
                        .WithOne("Report")
                        .HasForeignKey("ResiBuy.Server.Infrastructure.Model.Report", "OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Review", b =>
                {
                    b.HasOne("ResiBuy.Server.Infrastructure.Model.ProductDetail", "ProductDetail")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductDetailId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ResiBuy.Server.Infrastructure.Model.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ProductDetail");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Room", b =>
                {
                    b.HasOne("ResiBuy.Server.Infrastructure.Model.Building", "Building")
                        .WithMany("Rooms")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Building");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Shipper", b =>
                {
                    b.HasOne("ResiBuy.Server.Infrastructure.Model.Area", "LastLocation")
                        .WithMany("Shippers")
                        .HasForeignKey("LastLocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ResiBuy.Server.Infrastructure.Model.User", "User")
                        .WithOne()
                        .HasForeignKey("ResiBuy.Server.Infrastructure.Model.Shipper", "UserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("LastLocation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Store", b =>
                {
                    b.HasOne("ResiBuy.Server.Infrastructure.Model.User", "Owner")
                        .WithMany("Stores")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ResiBuy.Server.Infrastructure.Model.Room", "Room")
                        .WithMany("Stores")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.TimeSheet", b =>
                {
                    b.HasOne("ResiBuy.Server.Infrastructure.Model.Shipper", "Shipper")
                        .WithMany("TimeSheets")
                        .HasForeignKey("ShipperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shipper");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.UserNotification", b =>
                {
                    b.HasOne("ResiBuy.Server.Infrastructure.Model.Notification", "Notification")
                        .WithMany("UserNotifications")
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ResiBuy.Server.Infrastructure.Model.User", "User")
                        .WithMany("UserNotifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Notification");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.UserRoom", b =>
                {
                    b.HasOne("ResiBuy.Server.Infrastructure.Model.Room", "Room")
                        .WithMany("UserRooms")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ResiBuy.Server.Infrastructure.Model.User", "User")
                        .WithMany("UserRooms")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.UserVoucher", b =>
                {
                    b.HasOne("ResiBuy.Server.Infrastructure.Model.User", "User")
                        .WithMany("UserVouchers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ResiBuy.Server.Infrastructure.Model.Voucher", "Voucher")
                        .WithMany("UserVouchers")
                        .HasForeignKey("VoucherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Voucher");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Voucher", b =>
                {
                    b.HasOne("ResiBuy.Server.Infrastructure.Model.Store", "Store")
                        .WithMany("Vouchers")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Store");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Area", b =>
                {
                    b.Navigation("Buildings");

                    b.Navigation("Shippers");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Building", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Category", b =>
                {
                    b.Navigation("Image");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Notification", b =>
                {
                    b.Navigation("UserNotifications");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Order", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Report");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.OrderItem", b =>
                {
                    b.Navigation("Barcodes");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Product", b =>
                {
                    b.Navigation("ProductDetails");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.ProductDetail", b =>
                {
                    b.Navigation("AdditionalData");

                    b.Navigation("Barcodes");

                    b.Navigation("CartItems");

                    b.Navigation("Image");

                    b.Navigation("OrderItems");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Promotion", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Room", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Stores");

                    b.Navigation("UserRooms");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Shipper", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("TimeSheets");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Store", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Orders");

                    b.Navigation("Products");

                    b.Navigation("Vouchers");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.User", b =>
                {
                    b.Navigation("Avatar");

                    b.Navigation("Cart");

                    b.Navigation("Reports");

                    b.Navigation("Reviews");

                    b.Navigation("Stores");

                    b.Navigation("UserNotifications");

                    b.Navigation("UserRooms");

                    b.Navigation("UserVouchers");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Voucher", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("UserVouchers");
                });
#pragma warning restore 612, 618
        }
    }
}
