// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ResiBuy.Server.Infrastructure;

#nullable disable

namespace ResiBuy.Server.Migrations
{
    [DbContext(typeof(ResiBuyContext))]
<<<<<<<< HEAD:ResiBuy.Server/Migrations/20250920050427_updatebarcode.Designer.cs
    [Migration("20250920050427_updatebarcode")]
    partial class updatebarcode
========
    [Migration("20250917154623_barcodeInOrderItem")]
    partial class barcodeInOrderItem
>>>>>>>> e7e1633143d84933d061fb76c77f12f8e8e68034:ResiBuy.Server/Migrations/20250917154623_barcodeInOrderItem.Designer.cs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.AdditionalData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductDetailId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductDetailId");

                    b.ToTable("AdditionalDatas");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Area", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Areas");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsActive = true,
                            Latitude = 21.0227,
                            Longitude = 105.83629999999999,
                            Name = "Default Area"
                        });
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Barcode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

<<<<<<<< HEAD:ResiBuy.Server/Migrations/20250920050427_updatebarcode.Designer.cs
                    b.Property<Guid?>("OrderItemId")
========
                    b.Property<Guid>("OrderItemId")
>>>>>>>> e7e1633143d84933d061fb76c77f12f8e8e68034:ResiBuy.Server/Migrations/20250917154623_barcodeInOrderItem.Designer.cs
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ProductDetailId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderItemId");

                    b.HasIndex("ProductDetailId");

                    b.ToTable("Barcodes");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Building", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AreaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.ToTable("Buildings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            AreaId = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsActive = true,
                            Name = "Default Building"
                        });
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Cart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ExpiredCheckOutTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCheckingOut")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.CartItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CartId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ProductDetailId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductDetailId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
<<<<<<<< HEAD:ResiBuy.Server/Migrations/20250920050427_updatebarcode.Designer.cs
                            Id = new Guid("0d0d9c64-0fe3-48c4-908c-f79031b8cd34"),
========
                            Id = new Guid("39a9782f-feec-425c-be0d-67f40a3b65f5"),
>>>>>>>> e7e1633143d84933d061fb76c77f12f8e8e68034:ResiBuy.Server/Migrations/20250917154623_barcodeInOrderItem.Designer.cs
                            Name = "Đồ điện tử",
                            Status = true
                        },
                        new
                        {
<<<<<<<< HEAD:ResiBuy.Server/Migrations/20250920050427_updatebarcode.Designer.cs
                            Id = new Guid("10061822-c79f-4c9e-9854-efece04367eb"),
========
                            Id = new Guid("b7aa5882-e732-472a-9568-78918d38b672"),
>>>>>>>> e7e1633143d84933d061fb76c77f12f8e8e68034:ResiBuy.Server/Migrations/20250917154623_barcodeInOrderItem.Designer.cs
                            Name = "Thời trang",
                            Status = true
                        },
                        new
                        {
<<<<<<<< HEAD:ResiBuy.Server/Migrations/20250920050427_updatebarcode.Designer.cs
                            Id = new Guid("b43b860f-5c4d-46f2-ade9-dc00393775a7"),
========
                            Id = new Guid("8bc4e2cc-8fe0-4768-9e6b-ccd34e4b279f"),
>>>>>>>> e7e1633143d84933d061fb76c77f12f8e8e68034:ResiBuy.Server/Migrations/20250917154623_barcodeInOrderItem.Designer.cs
                            Name = "Đồ gia dụng",
                            Status = true
                        },
                        new
                        {
<<<<<<<< HEAD:ResiBuy.Server/Migrations/20250920050427_updatebarcode.Designer.cs
                            Id = new Guid("e14da67b-a367-4ade-b8c5-1c747e17da95"),
========
                            Id = new Guid("26e4baca-d351-44b7-87dd-f2b565ab6c32"),
>>>>>>>> e7e1633143d84933d061fb76c77f12f8e8e68034:ResiBuy.Server/Migrations/20250917154623_barcodeInOrderItem.Designer.cs
                            Name = "Sách",
                            Status = true
                        },
                        new
                        {
<<<<<<<< HEAD:ResiBuy.Server/Migrations/20250920050427_updatebarcode.Designer.cs
                            Id = new Guid("78e345fb-2b7c-4bf3-9045-4933ac2d69f7"),
========
                            Id = new Guid("e8d34a9b-1e1e-4205-918c-5c426e121370"),
>>>>>>>> e7e1633143d84933d061fb76c77f12f8e8e68034:ResiBuy.Server/Migrations/20250917154623_barcodeInOrderItem.Designer.cs
                            Name = "Thể thao",
                            Status = true
                        },
                        new
                        {
<<<<<<<< HEAD:ResiBuy.Server/Migrations/20250920050427_updatebarcode.Designer.cs
                            Id = new Guid("f0631fd8-66e0-4c32-8bee-5d8df34eb742"),
========
                            Id = new Guid("a9e26883-0e43-4aaf-bf28-cb48222186d7"),
>>>>>>>> e7e1633143d84933d061fb76c77f12f8e8e68034:ResiBuy.Server/Migrations/20250917154623_barcodeInOrderItem.Designer.cs
                            Name = "Mỹ phẩm",
                            Status = true
                        },
                        new
                        {
<<<<<<<< HEAD:ResiBuy.Server/Migrations/20250920050427_updatebarcode.Designer.cs
                            Id = new Guid("03876703-6872-4047-92d8-b91b4298da1d"),
========
                            Id = new Guid("98204ec9-d85c-45d0-af1b-de9763eebf32"),
>>>>>>>> e7e1633143d84933d061fb76c77f12f8e8e68034:ResiBuy.Server/Migrations/20250917154623_barcodeInOrderItem.Designer.cs
                            Name = "Đồ chơi",
                            Status = true
                        },
                        new
                        {
<<<<<<<< HEAD:ResiBuy.Server/Migrations/20250920050427_updatebarcode.Designer.cs
                            Id = new Guid("0e011096-01c0-40ee-9a56-5c83c565191d"),
========
                            Id = new Guid("12c7d55e-1368-4cfe-9aa4-a388ef0b9536"),
>>>>>>>> e7e1633143d84933d061fb76c77f12f8e8e68034:ResiBuy.Server/Migrations/20250917154623_barcodeInOrderItem.Designer.cs
                            Name = "Thực phẩm",
                            Status = true
                        },
                        new
                        {
<<<<<<<< HEAD:ResiBuy.Server/Migrations/20250920050427_updatebarcode.Designer.cs
                            Id = new Guid("d0adb9ae-e277-40b2-ac35-feb8be3821ad"),
========
                            Id = new Guid("2d30a554-5e4b-4820-aa35-90df30bdc2c1"),
>>>>>>>> e7e1633143d84933d061fb76c77f12f8e8e68034:ResiBuy.Server/Migrations/20250917154623_barcodeInOrderItem.Designer.cs
                            Name = "Phụ kiện",
                            Status = true
                        },
                        new
                        {
<<<<<<<< HEAD:ResiBuy.Server/Migrations/20250920050427_updatebarcode.Designer.cs
                            Id = new Guid("5b924576-a899-4447-9a60-051240f07111"),
========
                            Id = new Guid("e31b9fcd-272f-4174-bff3-5f5f8a23adf5"),
>>>>>>>> e7e1633143d84933d061fb76c77f12f8e8e68034:ResiBuy.Server/Migrations/20250917154623_barcodeInOrderItem.Designer.cs
                            Name = "Nội thất",
                            Status = true
                        },
                        new
                        {
<<<<<<<< HEAD:ResiBuy.Server/Migrations/20250920050427_updatebarcode.Designer.cs
                            Id = new Guid("3c1e0dd0-a37a-408a-abfd-cf2ec982081b"),
========
                            Id = new Guid("e04165f2-098b-4a45-8f9e-3cfac3aa2324"),
>>>>>>>> e7e1633143d84933d061fb76c77f12f8e8e68034:ResiBuy.Server/Migrations/20250917154623_barcodeInOrderItem.Designer.cs
                            Name = "Khác",
                            Status = true
                        });
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("StoreId");

                    b.ToTable("Event");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Image", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProductDetailId")
                        .HasColumnType("int");

                    b.Property<string>("ThumbUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId")
                        .IsUnique()
                        .HasFilter("[CategoryId] IS NOT NULL");

                    b.HasIndex("ProductDetailId")
                        .IsUnique()
                        .HasFilter("[ProductDetailId] IS NOT NULL");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
<<<<<<<< HEAD:ResiBuy.Server/Migrations/20250920050427_updatebarcode.Designer.cs
                            Id = "77c28899-d0b0-4327-b86a-43f541d7aaf9",
                            CategoryId = new Guid("0d0d9c64-0fe3-48c4-908c-f79031b8cd34"),
========
                            Id = "fd895a90-d2c0-4eb8-9ecd-881a8b092a7f",
                            CategoryId = new Guid("39a9782f-feec-425c-be0d-67f40a3b65f5"),
>>>>>>>> e7e1633143d84933d061fb76c77f12f8e8e68034:ResiBuy.Server/Migrations/20250917154623_barcodeInOrderItem.Designer.cs
                            Name = "thu-mua-do-dien-tu-1.jpg",
                            ThumbUrl = "http://res.cloudinary.com/dhz6zqwxx/image/upload/c_fill,h_300,w_300/string",
                            Url = "https://res.cloudinary.com/dhz6zqwxx/image/upload/v1756314488/string.jpg"
                        },
                        new
                        {
<<<<<<<< HEAD:ResiBuy.Server/Migrations/20250920050427_updatebarcode.Designer.cs
                            Id = "88eb39f6-103d-405a-b141-4374fc903493",
                            CategoryId = new Guid("10061822-c79f-4c9e-9854-efece04367eb"),
========
                            Id = "a30f9e5a-3f51-4f29-9cac-a2ce8e63d706",
                            CategoryId = new Guid("b7aa5882-e732-472a-9568-78918d38b672"),
>>>>>>>> e7e1633143d84933d061fb76c77f12f8e8e68034:ResiBuy.Server/Migrations/20250917154623_barcodeInOrderItem.Designer.cs
                            Name = "thoitrang.jpg",
                            ThumbUrl = "http://res.cloudinary.com/dhz6zqwxx/image/upload/c_fill,h_300,w_300/v1/resibuy/thoitrang_usekdn",
                            Url = "https://res.cloudinary.com/dhz6zqwxx/image/upload/v1756314610/resibuy/thoitrang_usekdn.jpg"
                        },
                        new
                        {
<<<<<<<< HEAD:ResiBuy.Server/Migrations/20250920050427_updatebarcode.Designer.cs
                            Id = "4b0175f0-6cc0-47ce-9c98-dc402fdff607",
                            CategoryId = new Guid("b43b860f-5c4d-46f2-ade9-dc00393775a7"),
========
                            Id = "704edbd1-8fdc-4ee9-8bd2-73554cdb25fe",
                            CategoryId = new Guid("8bc4e2cc-8fe0-4768-9e6b-ccd34e4b279f"),
>>>>>>>> e7e1633143d84933d061fb76c77f12f8e8e68034:ResiBuy.Server/Migrations/20250917154623_barcodeInOrderItem.Designer.cs
                            Name = "dogiadung.jpg",
                            ThumbUrl = "http://res.cloudinary.com/dhz6zqwxx/image/upload/c_fill,h_300,w_300/v1/resibuy/dogiadung_u5cuyh",
                            Url = "https://res.cloudinary.com/dhz6zqwxx/image/upload/v1756314610/resibuy/dogiadung_u5cuyh.jpg"
                        },
                        new
                        {
<<<<<<<< HEAD:ResiBuy.Server/Migrations/20250920050427_updatebarcode.Designer.cs
                            Id = "84cdab62-0c82-42e4-ad35-6f22f9c2950b",
                            CategoryId = new Guid("e14da67b-a367-4ade-b8c5-1c747e17da95"),
========
                            Id = "8c728ece-56f5-4857-97db-a1726b948d38",
                            CategoryId = new Guid("26e4baca-d351-44b7-87dd-f2b565ab6c32"),
>>>>>>>> e7e1633143d84933d061fb76c77f12f8e8e68034:ResiBuy.Server/Migrations/20250917154623_barcodeInOrderItem.Designer.cs
                            Name = "sach.jpg",
                            ThumbUrl = "http://res.cloudinary.com/dhz6zqwxx/image/upload/c_fill,h_300,w_300/v1/resibuy/sach_w9rqwe",
                            Url = "https://res.cloudinary.com/dhz6zqwxx/image/upload/v1756314610/resibuy/sach_w9rqwe.jpg"
                        },
                        new
                        {
<<<<<<<< HEAD:ResiBuy.Server/Migrations/20250920050427_updatebarcode.Designer.cs
                            Id = "a8c67b44-fe1f-4790-9b5a-4785ada8fd03",
                            CategoryId = new Guid("78e345fb-2b7c-4bf3-9045-4933ac2d69f7"),
========
                            Id = "ec2615ca-777f-47c4-84a7-27c47bbd1e2f",
                            CategoryId = new Guid("e8d34a9b-1e1e-4205-918c-5c426e121370"),
>>>>>>>> e7e1633143d84933d061fb76c77f12f8e8e68034:ResiBuy.Server/Migrations/20250917154623_barcodeInOrderItem.Designer.cs
                            Name = "thethao.jpg",
                            ThumbUrl = "http://res.cloudinary.com/dhz6zqwxx/image/upload/c_fill,h_300,w_300/v1/resibuy/thethao_mv34he",
                            Url = "https://res.cloudinary.com/dhz6zqwxx/image/upload/v1756314611/resibuy/thethao_mv34he.jpg"
                        },
                        new
                        {
<<<<<<<< HEAD:ResiBuy.Server/Migrations/20250920050427_updatebarcode.Designer.cs
                            Id = "a84be8ef-529b-4822-8b6b-2d171cb2a3b9",
                            CategoryId = new Guid("f0631fd8-66e0-4c32-8bee-5d8df34eb742"),
========
                            Id = "bc999001-77e6-4ed3-ac4c-e6330c6ac008",
                            CategoryId = new Guid("a9e26883-0e43-4aaf-bf28-cb48222186d7"),
>>>>>>>> e7e1633143d84933d061fb76c77f12f8e8e68034:ResiBuy.Server/Migrations/20250917154623_barcodeInOrderItem.Designer.cs
                            Name = "mypham.jpg",
                            ThumbUrl = "http://res.cloudinary.com/dhz6zqwxx/image/upload/c_fill,h_300,w_300/v1/resibuy/mypham_iltnhv",
                            Url = "https://res.cloudinary.com/dhz6zqwxx/image/upload/v1756314610/resibuy/mypham_iltnhv.jpg"
                        },
                        new
                        {
<<<<<<<< HEAD:ResiBuy.Server/Migrations/20250920050427_updatebarcode.Designer.cs
                            Id = "c0c80910-920b-42c3-aaad-e7b588ca2914",
                            CategoryId = new Guid("03876703-6872-4047-92d8-b91b4298da1d"),
========
                            Id = "ccc43e69-e202-4071-9de5-ebdd598149ec",
                            CategoryId = new Guid("98204ec9-d85c-45d0-af1b-de9763eebf32"),
>>>>>>>> e7e1633143d84933d061fb76c77f12f8e8e68034:ResiBuy.Server/Migrations/20250917154623_barcodeInOrderItem.Designer.cs
                            Name = "dochoi.png",
                            ThumbUrl = "http://res.cloudinary.com/dhz6zqwxx/image/upload/c_fill,h_300,w_300/v1/resibuy/dochoi_rz7pys",
                            Url = "https://res.cloudinary.com/dhz6zqwxx/image/upload/v1756314611/resibuy/dochoi_rz7pys.png"
                        },
                        new
                        {
<<<<<<<< HEAD:ResiBuy.Server/Migrations/20250920050427_updatebarcode.Designer.cs
                            Id = "0ad532eb-8a4e-45f3-94c7-11ae5846f7f8",
                            CategoryId = new Guid("0e011096-01c0-40ee-9a56-5c83c565191d"),
========
                            Id = "68f639df-7c05-4ec0-9596-d6cab85e15ef",
                            CategoryId = new Guid("12c7d55e-1368-4cfe-9aa4-a388ef0b9536"),
>>>>>>>> e7e1633143d84933d061fb76c77f12f8e8e68034:ResiBuy.Server/Migrations/20250917154623_barcodeInOrderItem.Designer.cs
                            Name = "thucpham.jpg",
                            ThumbUrl = "http://res.cloudinary.com/dhz6zqwxx/image/upload/c_fill,h_300,w_300/v1/resibuy/thucpham_la23wq",
                            Url = "https://res.cloudinary.com/dhz6zqwxx/image/upload/v1756314611/resibuy/thucpham_la23wq.jpg"
                        },
                        new
                        {
<<<<<<<< HEAD:ResiBuy.Server/Migrations/20250920050427_updatebarcode.Designer.cs
                            Id = "33a2efa6-a2a0-4530-a0f2-9fc2608cb944",
                            CategoryId = new Guid("d0adb9ae-e277-40b2-ac35-feb8be3821ad"),
========
                            Id = "c383e31b-61dc-4b37-ae38-716939fda554",
                            CategoryId = new Guid("2d30a554-5e4b-4820-aa35-90df30bdc2c1"),
>>>>>>>> e7e1633143d84933d061fb76c77f12f8e8e68034:ResiBuy.Server/Migrations/20250917154623_barcodeInOrderItem.Designer.cs
                            Name = "phukien.jpg",
                            ThumbUrl = "http://res.cloudinary.com/dhz6zqwxx/image/upload/c_fill,h_300,w_300/v1/resibuy/phukien_sct8nd",
                            Url = "https://res.cloudinary.com/dhz6zqwxx/image/upload/v1756314610/resibuy/phukien_sct8nd.jpg"
                        },
                        new
                        {
<<<<<<<< HEAD:ResiBuy.Server/Migrations/20250920050427_updatebarcode.Designer.cs
                            Id = "c499b9bd-d4b4-488b-a3a4-8a6a8734103e",
                            CategoryId = new Guid("5b924576-a899-4447-9a60-051240f07111"),
========
                            Id = "9d79be03-79e6-425a-b978-817fce688a1a",
                            CategoryId = new Guid("e31b9fcd-272f-4174-bff3-5f5f8a23adf5"),
>>>>>>>> e7e1633143d84933d061fb76c77f12f8e8e68034:ResiBuy.Server/Migrations/20250917154623_barcodeInOrderItem.Designer.cs
                            Name = "noithat.jpg",
                            ThumbUrl = "http://res.cloudinary.com/dhz6zqwxx/image/upload/c_fill,h_300,w_300/v1/resibuy/noithat_steelt",
                            Url = "https://res.cloudinary.com/dhz6zqwxx/image/upload/v1756314610/resibuy/noithat_steelt.jpg"
                        },
                        new
                        {
<<<<<<<< HEAD:ResiBuy.Server/Migrations/20250920050427_updatebarcode.Designer.cs
                            Id = "537ded3f-564b-42a9-869e-716bc0f5bf6d",
                            CategoryId = new Guid("3c1e0dd0-a37a-408a-abfd-cf2ec982081b"),
========
                            Id = "166fb455-622e-4e32-a369-aaa738c0a1a5",
                            CategoryId = new Guid("e04165f2-098b-4a45-8f9e-3cfac3aa2324"),
>>>>>>>> e7e1633143d84933d061fb76c77f12f8e8e68034:ResiBuy.Server/Migrations/20250917154623_barcodeInOrderItem.Designer.cs
                            Name = "khac1.jpg",
                            ThumbUrl = "http://res.cloudinary.com/dhz6zqwxx/image/upload/c_fill,h_300,w_300/other",
                            Url = "https://res.cloudinary.com/dhz6zqwxx/image/upload/v1756315891/other.jpg"
                        });
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Data")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReadBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CancelReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsReport")
                        .HasColumnType("bit");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("int");

                    b.Property<Guid?>("ShipperId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ShippingAddressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("ShippingFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid?>("VoucherId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ShipperId");

                    b.HasIndex("ShippingAddressId");

                    b.HasIndex("StoreId");

                    b.HasIndex("UserId");

                    b.HasIndex("VoucherId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.OrderItem", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductDetailId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductDetailId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Describe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsOutOfStock")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PromotionId")
                        .HasColumnType("int");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("WarrantyMonths")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("PromotionId");

                    b.HasIndex("StoreId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.ProductDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsOutOfStock")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Sold")
                        .HasColumnType("int");

                    b.Property<float>("Weight")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductDetails");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Promotion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Discount")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Promotions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Discount = 0,
<<<<<<<< HEAD:ResiBuy.Server/Migrations/20250920050427_updatebarcode.Designer.cs
                            EndDate = new DateTime(2225, 9, 20, 12, 4, 27, 441, DateTimeKind.Local).AddTicks(8472),
                            IsActive = false,
                            Name = "No Promotion",
                            StartDate = new DateTime(2025, 9, 20, 12, 4, 27, 441, DateTimeKind.Local).AddTicks(8471)
========
                            EndDate = new DateTime(2225, 9, 17, 22, 46, 22, 640, DateTimeKind.Local).AddTicks(2083),
                            IsActive = false,
                            Name = "No Promotion",
                            StartDate = new DateTime(2025, 9, 17, 22, 46, 22, 640, DateTimeKind.Local).AddTicks(2082)
>>>>>>>> e7e1633143d84933d061fb76c77f12f8e8e68034:ResiBuy.Server/Migrations/20250917154623_barcodeInOrderItem.Designer.cs
                        });
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.RefreshToken", b =>
                {
                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<string>("ReasonRevoked")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReplacedByToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Token");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Report", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("bit");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ReportTarget")
                        .HasColumnType("int");

                    b.Property<string>("TargetId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAnonymous")
                        .HasColumnType("bit");

                    b.Property<int>("ProductDetailId")
                        .HasColumnType("int");

                    b.Property<int>("Rate")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ProductDetailId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BuildingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            BuildingId = new Guid("22222222-2222-2222-2222-222222222222"),
                            IsActive = true,
                            Name = "Default Room"
                        });
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Shipper", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("EndWorkTime")
                        .HasColumnType("real");

                    b.Property<DateTime?>("FirstTimeLogin")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("bit");

                    b.Property<bool>("IsShipping")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastDelivered")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LastLocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ReportCount")
                        .HasColumnType("int");

                    b.Property<float>("StartWorkTime")
                        .HasColumnType("real");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("LastLocationId");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("Shippers");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Store", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPayFee")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("RoomId");

                    b.ToTable("Stores");

                    b.HasData(
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
<<<<<<<< HEAD:ResiBuy.Server/Migrations/20250920050427_updatebarcode.Designer.cs
                            CreatedAt = new DateTime(2025, 9, 20, 12, 4, 27, 441, DateTimeKind.Local).AddTicks(8465),
========
                            CreatedAt = new DateTime(2025, 9, 17, 22, 46, 22, 640, DateTimeKind.Local).AddTicks(2072),
>>>>>>>> e7e1633143d84933d061fb76c77f12f8e8e68034:ResiBuy.Server/Migrations/20250917154623_barcodeInOrderItem.Designer.cs
                            Description = "Default store for ResiBuy system",
                            IsLocked = false,
                            IsOpen = true,
                            IsPayFee = false,
                            Name = "ResiBuy",
                            OwnerId = "adm_df",
                            PhoneNumber = "0123456789",
                            RoomId = new Guid("33333333-3333-3333-3333-333333333333")
                        });
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.TimeSheet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateMark")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsLate")
                        .HasColumnType("bit");

                    b.Property<Guid>("ShipperId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ShipperId");

                    b.ToTable("TimeSheets");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AvatarId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdentityNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReportCount")
                        .HasColumnType("int");

                    b.Property<string>("Roles")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = "adm_df",
<<<<<<<< HEAD:ResiBuy.Server/Migrations/20250920050427_updatebarcode.Designer.cs
                            CreatedAt = new DateTime(2025, 9, 20, 12, 4, 27, 441, DateTimeKind.Local).AddTicks(8085),
========
                            CreatedAt = new DateTime(2025, 9, 17, 22, 46, 22, 640, DateTimeKind.Local).AddTicks(1091),
>>>>>>>> e7e1633143d84933d061fb76c77f12f8e8e68034:ResiBuy.Server/Migrations/20250917154623_barcodeInOrderItem.Designer.cs
                            DateOfBirth = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@123",
                            FullName = "Administrator",
                            IdentityNumber = "admin",
                            IsLocked = false,
<<<<<<<< HEAD:ResiBuy.Server/Migrations/20250920050427_updatebarcode.Designer.cs
                            PasswordHash = "$2a$11$nqRLMMFfnOMsr7kbgF53ROOqgcV8L31xizsiUCGANVG0a.RZMbNe.",
                            PhoneNumber = "admin",
                            ReportCount = 0,
                            Roles = "[\"ADMIN\"]",
                            UpdatedAt = new DateTime(2025, 9, 20, 12, 4, 27, 441, DateTimeKind.Local).AddTicks(8100)
========
                            PasswordHash = "$2a$11$nt8/cEpTnNxWx2V6rn5w1u/2X7.RaNArgoxH67u7XzVUYr0cFQq/q",
                            PhoneNumber = "admin",
                            ReportCount = 0,
                            Roles = "[\"ADMIN\"]",
                            UpdatedAt = new DateTime(2025, 9, 17, 22, 46, 22, 640, DateTimeKind.Local).AddTicks(1113)
>>>>>>>> e7e1633143d84933d061fb76c77f12f8e8e68034:ResiBuy.Server/Migrations/20250917154623_barcodeInOrderItem.Designer.cs
                        });
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.UserNotification", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("NotificationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "NotificationId");

                    b.HasIndex("NotificationId");

                    b.ToTable("UserNotifications");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.UserRoom", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoomId");

                    b.HasIndex("RoomId");

                    b.ToTable("UserRooms");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.UserVoucher", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("VoucherId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "VoucherId");

                    b.HasIndex("VoucherId");

                    b.ToTable("UserVouchers");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Voucher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("MaxDiscountPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MinOrderPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StoreId");

                    b.ToTable("Vouchers");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.AdditionalData", b =>
                {
                    b.HasOne("ResiBuy.Server.Infrastructure.Model.ProductDetail", "ProductDetail")
                        .WithMany("AdditionalData")
                        .HasForeignKey("ProductDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductDetail");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Barcode", b =>
                {
                    b.HasOne("ResiBuy.Server.Infrastructure.Model.OrderItem", "OrderItem")
                        .WithMany("Barcodes")
<<<<<<<< HEAD:ResiBuy.Server/Migrations/20250920050427_updatebarcode.Designer.cs
                        .HasForeignKey("OrderItemId");
========
                        .HasForeignKey("OrderItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
>>>>>>>> e7e1633143d84933d061fb76c77f12f8e8e68034:ResiBuy.Server/Migrations/20250917154623_barcodeInOrderItem.Designer.cs

                    b.HasOne("ResiBuy.Server.Infrastructure.Model.ProductDetail", "ProductDetail")
                        .WithMany("Barcodes")
                        .HasForeignKey("ProductDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderItem");

                    b.Navigation("ProductDetail");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Building", b =>
                {
                    b.HasOne("ResiBuy.Server.Infrastructure.Model.Area", "Area")
                        .WithMany("Buildings")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Cart", b =>
                {
                    b.HasOne("ResiBuy.Server.Infrastructure.Model.User", "User")
                        .WithOne("Cart")
                        .HasForeignKey("ResiBuy.Server.Infrastructure.Model.Cart", "UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.CartItem", b =>
                {
                    b.HasOne("ResiBuy.Server.Infrastructure.Model.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ResiBuy.Server.Infrastructure.Model.ProductDetail", "ProductDetail")
                        .WithMany("CartItems")
                        .HasForeignKey("ProductDetailId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("ProductDetail");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Event", b =>
                {
                    b.HasOne("ResiBuy.Server.Infrastructure.Model.Store", null)
                        .WithMany("Events")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Image", b =>
                {
                    b.HasOne("ResiBuy.Server.Infrastructure.Model.Category", "Category")
                        .WithOne("Image")
                        .HasForeignKey("ResiBuy.Server.Infrastructure.Model.Image", "CategoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ResiBuy.Server.Infrastructure.Model.ProductDetail", "ProductDetail")
                        .WithOne("Image")
                        .HasForeignKey("ResiBuy.Server.Infrastructure.Model.Image", "ProductDetailId");

                    b.HasOne("ResiBuy.Server.Infrastructure.Model.User", "User")
                        .WithOne("Avatar")
                        .HasForeignKey("ResiBuy.Server.Infrastructure.Model.Image", "UserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Category");

                    b.Navigation("ProductDetail");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Order", b =>
                {
                    b.HasOne("ResiBuy.Server.Infrastructure.Model.Shipper", "Shipper")
                        .WithMany("Orders")
                        .HasForeignKey("ShipperId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ResiBuy.Server.Infrastructure.Model.Room", "ShippingAddress")
                        .WithMany("Orders")
                        .HasForeignKey("ShippingAddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ResiBuy.Server.Infrastructure.Model.Store", "Store")
                        .WithMany("Orders")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ResiBuy.Server.Infrastructure.Model.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ResiBuy.Server.Infrastructure.Model.Voucher", "Voucher")
                        .WithMany("Orders")
                        .HasForeignKey("VoucherId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Shipper");

                    b.Navigation("ShippingAddress");

                    b.Navigation("Store");

                    b.Navigation("User");

                    b.Navigation("Voucher");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.OrderItem", b =>
                {
                    b.HasOne("ResiBuy.Server.Infrastructure.Model.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ResiBuy.Server.Infrastructure.Model.ProductDetail", "ProductDetail")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductDetailId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("ProductDetail");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Product", b =>
                {
                    b.HasOne("ResiBuy.Server.Infrastructure.Model.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ResiBuy.Server.Infrastructure.Model.Promotion", "Promotion")
                        .WithMany("Products")
                        .HasForeignKey("PromotionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("ResiBuy.Server.Infrastructure.Model.Store", "Store")
                        .WithMany("Products")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Promotion");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.ProductDetail", b =>
                {
                    b.HasOne("ResiBuy.Server.Infrastructure.Model.Product", "Product")
                        .WithMany("ProductDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.RefreshToken", b =>
                {
                    b.HasOne("ResiBuy.Server.Infrastructure.Model.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Report", b =>
                {
                    b.HasOne("ResiBuy.Server.Infrastructure.Model.User", "CreatedBy")
                        .WithMany("Reports")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ResiBuy.Server.Infrastructure.Model.Order", "Order")
                        .WithOne("Report")
                        .HasForeignKey("ResiBuy.Server.Infrastructure.Model.Report", "OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Review", b =>
                {
                    b.HasOne("ResiBuy.Server.Infrastructure.Model.ProductDetail", "ProductDetail")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductDetailId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ResiBuy.Server.Infrastructure.Model.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ProductDetail");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Room", b =>
                {
                    b.HasOne("ResiBuy.Server.Infrastructure.Model.Building", "Building")
                        .WithMany("Rooms")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Building");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Shipper", b =>
                {
                    b.HasOne("ResiBuy.Server.Infrastructure.Model.Area", "LastLocation")
                        .WithMany("Shippers")
                        .HasForeignKey("LastLocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ResiBuy.Server.Infrastructure.Model.User", "User")
                        .WithOne()
                        .HasForeignKey("ResiBuy.Server.Infrastructure.Model.Shipper", "UserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("LastLocation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Store", b =>
                {
                    b.HasOne("ResiBuy.Server.Infrastructure.Model.User", "Owner")
                        .WithMany("Stores")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ResiBuy.Server.Infrastructure.Model.Room", "Room")
                        .WithMany("Stores")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.TimeSheet", b =>
                {
                    b.HasOne("ResiBuy.Server.Infrastructure.Model.Shipper", "Shipper")
                        .WithMany("TimeSheets")
                        .HasForeignKey("ShipperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shipper");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.UserNotification", b =>
                {
                    b.HasOne("ResiBuy.Server.Infrastructure.Model.Notification", "Notification")
                        .WithMany("UserNotifications")
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ResiBuy.Server.Infrastructure.Model.User", "User")
                        .WithMany("UserNotifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Notification");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.UserRoom", b =>
                {
                    b.HasOne("ResiBuy.Server.Infrastructure.Model.Room", "Room")
                        .WithMany("UserRooms")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ResiBuy.Server.Infrastructure.Model.User", "User")
                        .WithMany("UserRooms")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.UserVoucher", b =>
                {
                    b.HasOne("ResiBuy.Server.Infrastructure.Model.User", "User")
                        .WithMany("UserVouchers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ResiBuy.Server.Infrastructure.Model.Voucher", "Voucher")
                        .WithMany("UserVouchers")
                        .HasForeignKey("VoucherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Voucher");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Voucher", b =>
                {
                    b.HasOne("ResiBuy.Server.Infrastructure.Model.Store", "Store")
                        .WithMany("Vouchers")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Store");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Area", b =>
                {
                    b.Navigation("Buildings");

                    b.Navigation("Shippers");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Building", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Category", b =>
                {
                    b.Navigation("Image");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Notification", b =>
                {
                    b.Navigation("UserNotifications");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Order", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Report");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.OrderItem", b =>
                {
                    b.Navigation("Barcodes");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Product", b =>
                {
                    b.Navigation("ProductDetails");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.ProductDetail", b =>
                {
                    b.Navigation("AdditionalData");

                    b.Navigation("Barcodes");

                    b.Navigation("CartItems");

                    b.Navigation("Image");

                    b.Navigation("OrderItems");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Promotion", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Room", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Stores");

                    b.Navigation("UserRooms");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Shipper", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("TimeSheets");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Store", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Orders");

                    b.Navigation("Products");

                    b.Navigation("Vouchers");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.User", b =>
                {
                    b.Navigation("Avatar");

                    b.Navigation("Cart");

                    b.Navigation("Reports");

                    b.Navigation("Reviews");

                    b.Navigation("Stores");

                    b.Navigation("UserNotifications");

                    b.Navigation("UserRooms");

                    b.Navigation("UserVouchers");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Voucher", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("UserVouchers");
                });
#pragma warning restore 612, 618
        }
    }
}
