// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ResiBuy.Server.Infrastructure;

#nullable disable

namespace ResiBuy.Server.Migrations
{
    [DbContext(typeof(ResiBuyContext))]
    partial class ResiBuyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.AdditionalData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductDetailId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductDetailId");

                    b.ToTable("AdditionalDatas");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Area", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Areas");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsActive = true,
                            Latitude = 21.0227,
                            Longitude = 105.83629999999999,
                            Name = "Default Area"
                        });
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Building", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AreaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.ToTable("Buildings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            AreaId = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsActive = true,
                            Name = "Default Building"
                        });
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Cart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ExpiredCheckOutTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCheckingOut")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.CartItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CartId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ProductDetailId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductDetailId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9a902a27-b9af-4167-8c49-88b866b5f66e"),
                            Name = "Đồ điện tử",
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("59fb90b2-94aa-4be3-a7ce-e68207e47d0f"),
                            Name = "Thời trang",
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("2b8011c1-85f9-44eb-afc7-49dbcdfc2a73"),
                            Name = "Đồ gia dụng",
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("bb608469-80f7-4218-8470-9034d9dcc4ff"),
                            Name = "Sách",
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("81fe9380-98eb-463b-a6c9-c62fae606249"),
                            Name = "Thể thao",
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("6ae4d8c1-48af-496c-945e-b47bba80e9bf"),
                            Name = "Mỹ phẩm",
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("2e40482e-8569-4ad3-9e14-1196d1a0d588"),
                            Name = "Đồ chơi",
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("72a1e78f-f43e-4bd7-857b-b7ba9e5421e3"),
                            Name = "Thực phẩm",
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("4a471b55-2bd1-4171-b7da-9db1ce456a19"),
                            Name = "Phụ kiện",
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("ff1e4b27-922b-4a6d-b6ef-1c4168028728"),
                            Name = "Nội thất",
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("4159de0c-105f-48bb-aaf9-332be8e118f4"),
                            Name = "Khác",
                            Status = true
                        });
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("StoreId");

                    b.ToTable("Event");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Image", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProductDetailId")
                        .HasColumnType("int");

                    b.Property<string>("ThumbUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId")
                        .IsUnique()
                        .HasFilter("[CategoryId] IS NOT NULL");

                    b.HasIndex("ProductDetailId")
                        .IsUnique()
                        .HasFilter("[ProductDetailId] IS NOT NULL");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            Id = "337a1dca-fa3f-49a0-a6ed-96091533a2fc",
                            CategoryId = new Guid("9a902a27-b9af-4167-8c49-88b866b5f66e"),
                            Name = "thu-mua-do-dien-tu-1.jpg",
                            ThumbUrl = "http://res.cloudinary.com/dhz6zqwxx/image/upload/c_fill,h_300,w_300/string",
                            Url = "https://res.cloudinary.com/dhz6zqwxx/image/upload/v1756314488/string.jpg"
                        },
                        new
                        {
                            Id = "2dd836a4-5aae-4b1d-ba71-e1bf0626ae9b",
                            CategoryId = new Guid("59fb90b2-94aa-4be3-a7ce-e68207e47d0f"),
                            Name = "thoitrang.jpg",
                            ThumbUrl = "http://res.cloudinary.com/dhz6zqwxx/image/upload/c_fill,h_300,w_300/v1/resibuy/thoitrang_usekdn",
                            Url = "https://res.cloudinary.com/dhz6zqwxx/image/upload/v1756314610/resibuy/thoitrang_usekdn.jpg"
                        },
                        new
                        {
                            Id = "09202e2a-c6a2-49bd-8119-9ea1f9bfc07b",
                            CategoryId = new Guid("2b8011c1-85f9-44eb-afc7-49dbcdfc2a73"),
                            Name = "dogiadung.jpg",
                            ThumbUrl = "http://res.cloudinary.com/dhz6zqwxx/image/upload/c_fill,h_300,w_300/v1/resibuy/dogiadung_u5cuyh",
                            Url = "https://res.cloudinary.com/dhz6zqwxx/image/upload/v1756314610/resibuy/dogiadung_u5cuyh.jpg"
                        },
                        new
                        {
                            Id = "3b9a1516-989a-4dc7-88c0-e24b6c858a66",
                            CategoryId = new Guid("bb608469-80f7-4218-8470-9034d9dcc4ff"),
                            Name = "sach.jpg",
                            ThumbUrl = "http://res.cloudinary.com/dhz6zqwxx/image/upload/c_fill,h_300,w_300/v1/resibuy/sach_w9rqwe",
                            Url = "https://res.cloudinary.com/dhz6zqwxx/image/upload/v1756314610/resibuy/sach_w9rqwe.jpg"
                        },
                        new
                        {
                            Id = "86b0532d-bf59-4492-8b57-516be4e3b035",
                            CategoryId = new Guid("81fe9380-98eb-463b-a6c9-c62fae606249"),
                            Name = "thethao.jpg",
                            ThumbUrl = "http://res.cloudinary.com/dhz6zqwxx/image/upload/c_fill,h_300,w_300/v1/resibuy/thethao_mv34he",
                            Url = "https://res.cloudinary.com/dhz6zqwxx/image/upload/v1756314611/resibuy/thethao_mv34he.jpg"
                        },
                        new
                        {
                            Id = "f1f9c7a9-616e-4a08-a31f-59b10a104b95",
                            CategoryId = new Guid("6ae4d8c1-48af-496c-945e-b47bba80e9bf"),
                            Name = "mypham.jpg",
                            ThumbUrl = "http://res.cloudinary.com/dhz6zqwxx/image/upload/c_fill,h_300,w_300/v1/resibuy/mypham_iltnhv",
                            Url = "https://res.cloudinary.com/dhz6zqwxx/image/upload/v1756314610/resibuy/mypham_iltnhv.jpg"
                        },
                        new
                        {
                            Id = "b3b91ad5-a2d4-4dfb-ad0b-fd45df1e9591",
                            CategoryId = new Guid("2e40482e-8569-4ad3-9e14-1196d1a0d588"),
                            Name = "dochoi.png",
                            ThumbUrl = "http://res.cloudinary.com/dhz6zqwxx/image/upload/c_fill,h_300,w_300/v1/resibuy/dochoi_rz7pys",
                            Url = "https://res.cloudinary.com/dhz6zqwxx/image/upload/v1756314611/resibuy/dochoi_rz7pys.png"
                        },
                        new
                        {
                            Id = "0f02d5a6-0ae3-4473-9a00-2f3d03506fa4",
                            CategoryId = new Guid("72a1e78f-f43e-4bd7-857b-b7ba9e5421e3"),
                            Name = "thucpham.jpg",
                            ThumbUrl = "http://res.cloudinary.com/dhz6zqwxx/image/upload/c_fill,h_300,w_300/v1/resibuy/thucpham_la23wq",
                            Url = "https://res.cloudinary.com/dhz6zqwxx/image/upload/v1756314611/resibuy/thucpham_la23wq.jpg"
                        },
                        new
                        {
                            Id = "f9a480a7-1f50-4446-86d7-dc2aef3c1eeb",
                            CategoryId = new Guid("4a471b55-2bd1-4171-b7da-9db1ce456a19"),
                            Name = "phukien.jpg",
                            ThumbUrl = "http://res.cloudinary.com/dhz6zqwxx/image/upload/c_fill,h_300,w_300/v1/resibuy/phukien_sct8nd",
                            Url = "https://res.cloudinary.com/dhz6zqwxx/image/upload/v1756314610/resibuy/phukien_sct8nd.jpg"
                        },
                        new
                        {
                            Id = "4920aaf0-176c-4e1a-bd52-a16519849758",
                            CategoryId = new Guid("ff1e4b27-922b-4a6d-b6ef-1c4168028728"),
                            Name = "noithat.jpg",
                            ThumbUrl = "http://res.cloudinary.com/dhz6zqwxx/image/upload/c_fill,h_300,w_300/v1/resibuy/noithat_steelt",
                            Url = "https://res.cloudinary.com/dhz6zqwxx/image/upload/v1756314610/resibuy/noithat_steelt.jpg"
                        },
                        new
                        {
                            Id = "d7a19834-211d-4f75-8c81-88892d48c4c4",
                            CategoryId = new Guid("4159de0c-105f-48bb-aaf9-332be8e118f4"),
                            Name = "khac1.jpg",
                            ThumbUrl = "http://res.cloudinary.com/dhz6zqwxx/image/upload/c_fill,h_300,w_300/other",
                            Url = "https://res.cloudinary.com/dhz6zqwxx/image/upload/v1756315891/other.jpg"
                        });
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Data")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReadBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CancelReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsReport")
                        .HasColumnType("bit");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("int");

                    b.Property<Guid?>("ShipperId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ShippingAddressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("ShippingFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid?>("VoucherId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ShipperId");

                    b.HasIndex("ShippingAddressId");

                    b.HasIndex("StoreId");

                    b.HasIndex("UserId");

                    b.HasIndex("VoucherId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.OrderItem", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductDetailId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductDetailId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Describe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsOutOfStock")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PromotionId")
                        .HasColumnType("int");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("PromotionId");

                    b.HasIndex("StoreId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.ProductDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsOutOfStock")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Sold")
                        .HasColumnType("int");

                    b.Property<float>("Weight")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductDetails");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Promotion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Discount")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Promotions");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.RefreshToken", b =>
                {
                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<string>("ReasonRevoked")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReplacedByToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Token");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Report", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("bit");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ReportTarget")
                        .HasColumnType("int");

                    b.Property<string>("TargetId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAnonymous")
                        .HasColumnType("bit");

                    b.Property<int>("ProductDetailId")
                        .HasColumnType("int");

                    b.Property<int>("Rate")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ProductDetailId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BuildingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            BuildingId = new Guid("22222222-2222-2222-2222-222222222222"),
                            IsActive = true,
                            Name = "Default Room"
                        });
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Shipper", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("EndWorkTime")
                        .HasColumnType("real");

                    b.Property<DateTime?>("FirstTimeLogin")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("bit");

                    b.Property<bool>("IsShipping")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastDelivered")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LastLocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ReportCount")
                        .HasColumnType("int");

                    b.Property<float>("StartWorkTime")
                        .HasColumnType("real");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("LastLocationId");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("Shippers");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Store", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPayFee")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("RoomId");

                    b.ToTable("Stores");

                    b.HasData(
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            CreatedAt = new DateTime(2025, 9, 7, 14, 13, 31, 150, DateTimeKind.Local).AddTicks(7853),
                            Description = "Default store for ResiBuy system",
                            IsLocked = false,
                            IsOpen = true,
                            IsPayFee = false,
                            Name = "ResiBuy",
                            OwnerId = "adm_df",
                            PhoneNumber = "0123456789",
                            RoomId = new Guid("33333333-3333-3333-3333-333333333333")
                        });
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.TimeSheet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateMark")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsLate")
                        .HasColumnType("bit");

                    b.Property<Guid>("ShipperId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ShipperId");

                    b.ToTable("TimeSheets");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AvatarId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdentityNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReportCount")
                        .HasColumnType("int");

                    b.Property<string>("Roles")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = "adm_df",
                            CreatedAt = new DateTime(2025, 9, 7, 14, 13, 31, 150, DateTimeKind.Local).AddTicks(7400),
                            DateOfBirth = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@123",
                            FullName = "Administrator",
                            IdentityNumber = "admin",
                            IsLocked = false,
                            PasswordHash = "$2a$11$mso1tAsshOF6A3R7ZzAAv.qjr60TjfCk5yTFarKIjqK05Pjf0321i",
                            PhoneNumber = "admin",
                            ReportCount = 0,
                            Roles = "[\"ADMIN\"]",
                            UpdatedAt = new DateTime(2025, 9, 7, 14, 13, 31, 150, DateTimeKind.Local).AddTicks(7413)
                        });
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.UserNotification", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("NotificationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "NotificationId");

                    b.HasIndex("NotificationId");

                    b.ToTable("UserNotifications");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.UserRoom", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoomId");

                    b.HasIndex("RoomId");

                    b.ToTable("UserRooms");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.UserVoucher", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("VoucherId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "VoucherId");

                    b.HasIndex("VoucherId");

                    b.ToTable("UserVouchers");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Voucher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("MaxDiscountPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MinOrderPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StoreId");

                    b.ToTable("Vouchers");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.AdditionalData", b =>
                {
                    b.HasOne("ResiBuy.Server.Infrastructure.Model.ProductDetail", "ProductDetail")
                        .WithMany("AdditionalData")
                        .HasForeignKey("ProductDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductDetail");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Building", b =>
                {
                    b.HasOne("ResiBuy.Server.Infrastructure.Model.Area", "Area")
                        .WithMany("Buildings")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Cart", b =>
                {
                    b.HasOne("ResiBuy.Server.Infrastructure.Model.User", "User")
                        .WithOne("Cart")
                        .HasForeignKey("ResiBuy.Server.Infrastructure.Model.Cart", "UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.CartItem", b =>
                {
                    b.HasOne("ResiBuy.Server.Infrastructure.Model.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ResiBuy.Server.Infrastructure.Model.ProductDetail", "ProductDetail")
                        .WithMany("CartItems")
                        .HasForeignKey("ProductDetailId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("ProductDetail");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Event", b =>
                {
                    b.HasOne("ResiBuy.Server.Infrastructure.Model.Store", null)
                        .WithMany("Events")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Image", b =>
                {
                    b.HasOne("ResiBuy.Server.Infrastructure.Model.Category", "Category")
                        .WithOne("Image")
                        .HasForeignKey("ResiBuy.Server.Infrastructure.Model.Image", "CategoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ResiBuy.Server.Infrastructure.Model.ProductDetail", "ProductDetail")
                        .WithOne("Image")
                        .HasForeignKey("ResiBuy.Server.Infrastructure.Model.Image", "ProductDetailId");

                    b.HasOne("ResiBuy.Server.Infrastructure.Model.User", "User")
                        .WithOne("Avatar")
                        .HasForeignKey("ResiBuy.Server.Infrastructure.Model.Image", "UserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Category");

                    b.Navigation("ProductDetail");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Order", b =>
                {
                    b.HasOne("ResiBuy.Server.Infrastructure.Model.Shipper", "Shipper")
                        .WithMany("Orders")
                        .HasForeignKey("ShipperId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ResiBuy.Server.Infrastructure.Model.Room", "ShippingAddress")
                        .WithMany("Orders")
                        .HasForeignKey("ShippingAddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ResiBuy.Server.Infrastructure.Model.Store", "Store")
                        .WithMany("Orders")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ResiBuy.Server.Infrastructure.Model.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ResiBuy.Server.Infrastructure.Model.Voucher", "Voucher")
                        .WithMany("Orders")
                        .HasForeignKey("VoucherId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Shipper");

                    b.Navigation("ShippingAddress");

                    b.Navigation("Store");

                    b.Navigation("User");

                    b.Navigation("Voucher");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.OrderItem", b =>
                {
                    b.HasOne("ResiBuy.Server.Infrastructure.Model.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ResiBuy.Server.Infrastructure.Model.ProductDetail", "ProductDetail")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductDetailId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("ProductDetail");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Product", b =>
                {
                    b.HasOne("ResiBuy.Server.Infrastructure.Model.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ResiBuy.Server.Infrastructure.Model.Promotion", "Promotion")
                        .WithMany("Products")
                        .HasForeignKey("PromotionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ResiBuy.Server.Infrastructure.Model.Store", "Store")
                        .WithMany("Products")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Promotion");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.ProductDetail", b =>
                {
                    b.HasOne("ResiBuy.Server.Infrastructure.Model.Product", "Product")
                        .WithMany("ProductDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.RefreshToken", b =>
                {
                    b.HasOne("ResiBuy.Server.Infrastructure.Model.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Report", b =>
                {
                    b.HasOne("ResiBuy.Server.Infrastructure.Model.User", "CreatedBy")
                        .WithMany("Reports")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ResiBuy.Server.Infrastructure.Model.Order", "Order")
                        .WithOne("Report")
                        .HasForeignKey("ResiBuy.Server.Infrastructure.Model.Report", "OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Review", b =>
                {
                    b.HasOne("ResiBuy.Server.Infrastructure.Model.ProductDetail", "ProductDetail")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductDetailId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ResiBuy.Server.Infrastructure.Model.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ProductDetail");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Room", b =>
                {
                    b.HasOne("ResiBuy.Server.Infrastructure.Model.Building", "Building")
                        .WithMany("Rooms")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Building");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Shipper", b =>
                {
                    b.HasOne("ResiBuy.Server.Infrastructure.Model.Area", "LastLocation")
                        .WithMany("Shippers")
                        .HasForeignKey("LastLocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ResiBuy.Server.Infrastructure.Model.User", "User")
                        .WithOne()
                        .HasForeignKey("ResiBuy.Server.Infrastructure.Model.Shipper", "UserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("LastLocation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Store", b =>
                {
                    b.HasOne("ResiBuy.Server.Infrastructure.Model.User", "Owner")
                        .WithMany("Stores")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ResiBuy.Server.Infrastructure.Model.Room", "Room")
                        .WithMany("Stores")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.TimeSheet", b =>
                {
                    b.HasOne("ResiBuy.Server.Infrastructure.Model.Shipper", "Shipper")
                        .WithMany("TimeSheets")
                        .HasForeignKey("ShipperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shipper");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.UserNotification", b =>
                {
                    b.HasOne("ResiBuy.Server.Infrastructure.Model.Notification", "Notification")
                        .WithMany("UserNotifications")
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ResiBuy.Server.Infrastructure.Model.User", "User")
                        .WithMany("UserNotifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Notification");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.UserRoom", b =>
                {
                    b.HasOne("ResiBuy.Server.Infrastructure.Model.Room", "Room")
                        .WithMany("UserRooms")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ResiBuy.Server.Infrastructure.Model.User", "User")
                        .WithMany("UserRooms")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.UserVoucher", b =>
                {
                    b.HasOne("ResiBuy.Server.Infrastructure.Model.User", "User")
                        .WithMany("UserVouchers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ResiBuy.Server.Infrastructure.Model.Voucher", "Voucher")
                        .WithMany("UserVouchers")
                        .HasForeignKey("VoucherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Voucher");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Voucher", b =>
                {
                    b.HasOne("ResiBuy.Server.Infrastructure.Model.Store", "Store")
                        .WithMany("Vouchers")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Store");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Area", b =>
                {
                    b.Navigation("Buildings");

                    b.Navigation("Shippers");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Building", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Category", b =>
                {
                    b.Navigation("Image");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Notification", b =>
                {
                    b.Navigation("UserNotifications");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Order", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Report");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Product", b =>
                {
                    b.Navigation("ProductDetails");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.ProductDetail", b =>
                {
                    b.Navigation("AdditionalData");

                    b.Navigation("CartItems");

                    b.Navigation("Image");

                    b.Navigation("OrderItems");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Promotion", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Room", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Stores");

                    b.Navigation("UserRooms");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Shipper", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("TimeSheets");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Store", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Orders");

                    b.Navigation("Products");

                    b.Navigation("Vouchers");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.User", b =>
                {
                    b.Navigation("Avatar");

                    b.Navigation("Cart");

                    b.Navigation("Reports");

                    b.Navigation("Reviews");

                    b.Navigation("Stores");

                    b.Navigation("UserNotifications");

                    b.Navigation("UserRooms");

                    b.Navigation("UserVouchers");
                });

            modelBuilder.Entity("ResiBuy.Server.Infrastructure.Model.Voucher", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("UserVouchers");
                });
#pragma warning restore 612, 618
        }
    }
}
